name: Update Follower Count

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  update-follower-count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Follower Count
        id: get_followers
        run: |
          FOLLOWER_COUNT=$(curl -s https://api.github.com/users/kchan21 | jq '.followers')
          echo "followers=${FOLLOWER_COUNT}" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i 's/Followers: [0-9]*/Followers: '"$followers"'/' README.md
          
      - name: Commit and Push Changes
        run: |
          git config --local user.email "your_email@example.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          git commit -m "Update follower count to $followers"
          git push
