name: Update Follower Count

permissions:
  contents: write  # Allow write access to repository contents

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  update-follower-count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Current Follower Count
        id: get_followers
        run: |
          # Extract the current follower count from README.md
          CURRENT_COUNT=$(grep -oP 'Followers: \K[0-9]+' README.md)
          echo "current_count=${CURRENT_COUNT}" >> $GITHUB_ENV
          echo "Current follower count: ${CURRENT_COUNT}"  # Print the current count

      - name: Increment Follower Count
        id: increment_count
        run: |
          # Increment the current count by 1
          NEW_COUNT=$((current_count + 1))
          echo "new_count=${NEW_COUNT}" >> $GITHUB_ENV
          echo "New follower count: ${NEW_COUNT}"  # Print the new count

      - name: Update README
        run: |
          sed -i 's|<span id="follower-count">Followers: [0-9]*</span>|<span id="follower-count">Followers: '"$new_count"'</span>|' README.md
          echo "Contents of README.md after update:"
          cat README.md  # Print the updated README.md for debugging

      - name: Commit and Push Changes
        run: |
          git config --local user.email "your_email@example.com"  # Your email here
          git config --local user.name "GitHub Actions"
          git add README.md
          git commit -m "Increment follower count to $new_count" || echo "No changes to commit"
          git push origin main  # Use the GITHUB_TOKEN for pushing
